# Generated by Django 3.0.4 on 2020-05-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200505_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorship',
            name='author_contribution',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>_<django.db.models.fields.related.ForeignKey>', max_length=255, unique=True),
        ),
    ]
