# Generated by Django 3.0.4 on 2020-05-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_authorship_author_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorship',
            name='author_contribution',
        ),
        migrations.AddConstraint(
            model_name='authorship',
            constraint=models.UniqueConstraint(fields=('author', 'contribution'), name='unique_author_contribution'),
        ),
    ]
