# Generated by Django 3.0.4 on 2020-05-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200506_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='registration_period',
        ),
    ]
