# Generated by Django 3.0.4 on 2020-05-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contribution_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='fee_payed',
            field=models.BooleanField(default=False),
        ),
    ]
